Increment libuv version and fix compilation problem under win32
indutny/uv_link_t pull request #3
Opened 2017-06-11 14:02 UTC by odiszapc

Bump libuv version to 1.12.0
Fix compilation issues on Windows platform

2017-06-11 14:28 UTC, refack approved these changes
LGTM

2017-06-11 14:29 UTC, refack commented
FWIW I'd split the bump and windows compact.
Confirm that this works:
```cmd
c:\code\4node\uv_link_t$ gypkg build uv_link_t.gyp
[====================================================================================================] 0.0s ninja: Entering directory `out\Release'
[35/50] CC obj\src\uv_link_t.uv_link_observer_t.obj
c:\code\4node\uv_link_t\src\uv_link_observer_t.c(17): warning C4098: 'uv_link_observer_read_cb': 'void' function returning a value
[36/50] CC obj\src\uv_link_t.uv_link_t.obj
c:\code\4node\uv_link_t\src\uv_link_t.c(124): warning C4098: 'uv_link_close_join': 'void' function returning a value
[38/50] CC obj\src\uv_link_t.defaults.obj
c:\code\4node\uv_link_t\src\defaults.c(54): warning C4098: 'uv_link_default_alloc_cb_override': 'void' function returning a value
c:\code\4node\uv_link_t\src\defaults.c(61): warning C4098: 'uv_link_default_read_cb_override': 'void' function returning a value
[50/50] LINK uv_link_t-example.exe

c:\code\4node\uv_link_t$ echo %ERRORLEVEL%
0
```

2017-06-11 15:49 UTC, odiszapc commented
Should I do something more? Thx!

2017-06-11 15:49 UTC, odiszapc commented
Also similar changes to uv_ssl_t: https://github.com/indutny/uv_ssl_t/pull/4

2017-06-11 17:08 UTC, indutny requested changes

2017-06-11 17:08 UTC, indutny commented on test/src/test-uv-link-source-t.c
>    CHECK_EQ(socketpair(AF_UNIX, SOCK_STREAM, 0, fds), 0, "socketpair()");
Well, it will compile, but the test won't work at all :) Let's `ifndef` whole test implementation

2017-06-11 17:08 UTC, indutny commented on uv_link_t.gyp
> +      "git://github.com/libuv/libuv.git@^1.12.0 => uv.gyp:libuv",
Strange... I think it should automatically pick `1.12.0`, because `^1.9.0` allows this. Why is it needed?

2017-06-12 04:46 UTC, odiszapc commented on test/src/test-uv-link-source-t.c
>    CHECK_EQ(socketpair(AF_UNIX, SOCK_STREAM, 0, fds), 0, "socketpair()");
Done.

2017-06-12 04:46 UTC, odiszapc commented on uv_link_t.gyp
> +      "git://github.com/libuv/libuv.git@^1.12.0 => uv.gyp:libuv",
Done

2017-06-12 11:10 UTC, refack commented
latest change is a regression :(
```
c:\code\4node\uv_link_t$ gypkg build uv_link_t.gyp
[====================================================================================================] 0.0s ninja: Entering directory `out\Release'
[1/1] LINK uv_link_t-test.exe
FAILED: uv_link_t-test.exe
ninja -t msvc -e environment.x64 -- link.exe /nologo /OUT:uv_link_t-test.exe @uv_link_t-test.exe.rsp
uv_link_t-test.main.obj : error LNK2019: unresolved external symbol test__uv_link_source_t referenced in function main
uv_link_t-test.exe : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.
child_process.js:611
    throw err;
```

2017-06-12 14:03 UTC, odiszapc commented
@refack Oops, I cant wrap `TEST_IMPL` with` #ifndef`. Fixed it. No it compiles. Please check it. Thx!

2017-06-12 16:04 UTC, refack commented
Compiles 👍 
(but need new version of `mini-test` for the test to work on Windows https://github.com/indutny/mini-test.c/issues/6)
```
c:\code\4node\uv_link_t\out\Release$ ninja
[29/46] CC obj\src\uv_link_t.uv_link_observer_t.obj
c:\code\4node\uv_link_t\src\uv_link_observer_t.c(17): warning C4098: 'uv_link_observer_read_cb': 'void' function returning a value
[31/46] CC obj\src\uv_link_t.defaults.obj
c:\code\4node\uv_link_t\src\defaults.c(54): warning C4098: 'uv_link_default_alloc_cb_override': 'void' function returning a value
c:\code\4node\uv_link_t\src\defaults.c(61): warning C4098: 'uv_link_default_read_cb_override': 'void' function returning a value
[34/46] CC obj\src\uv_link_t.uv_link_t.obj
c:\code\4node\uv_link_t\src\uv_link_t.c(124): warning C4098: 'uv_link_close_join': 'void' function returning a value
[46/46] LINK uv_link_t-test.exe

c:\code\4node\uv_link_t\out\Release$ uv_link_t-test.exe
# Assertion failure: "implement me"

c:\code\4node\uv_link_t\out\Release$ echo %ERRORLEVEL%
-1073740791
```

2017-06-13 13:17 UTC, odiszapc commented
@refack Fixed by moving to minitest.c master (Don't see tags or branches, sorry). No 
```
C:\projects\uv_link_t>C:\ClionProjects\uv_link_t\out\Release\uv_link_t-test.exe
1..5
ok - uv_link_source_t
ok - uv_link_observer_t
ok - close_depth
ok - stop_read_on_error
ok - strerror
```

2017-06-13 20:15 UTC, indutny requested changes
Two last nits, otherwise LGTM. Thank you!

2017-06-13 20:15 UTC, indutny commented on uv_link_t.gyp
> -        "git://github.com/indutny/mini-test.c.git@^1.0.0 => mini-test.gyp:mini-test",
This may be reverted now, I just released `1.1.1` with all changes.

2017-06-13 20:15 UTC, indutny commented on test/src/test-uv-link-source-t.c
> -
Superfluous  changes.

2017-06-13 20:16 UTC, indutny commented on test/src/test-common.h
> +#include <winsock2.h>
Sorry, few more nits that I forgot to mention. Lets ident these includes with space between `#` and `include: `# include`.

2017-06-13 20:17 UTC, indutny commented on test/src/test-common.h
> +#endif
`#endif  /* _WIN32 */`

2017-06-13 20:17 UTC, indutny commented on test/src/test-uv-link-source-t.c
> +#endif
`#endif  /* !_WIN32 */`

2017-06-14 12:17 UTC, odiszapc commented on uv_link_t.gyp
> -        "git://github.com/indutny/mini-test.c.git@^1.0.0 => mini-test.gyp:mini-test",
Done.

2017-06-14 12:17 UTC, odiszapc commented on test/src/test-uv-link-source-t.c
> -
Done.

2017-06-14 12:17 UTC, odiszapc commented on test/src/test-common.h
> +#include <winsock2.h>
Done.

2017-06-14 12:17 UTC, odiszapc commented on test/src/test-common.h
> +#endif
Done.

2017-06-14 12:17 UTC, odiszapc commented on test/src/test-uv-link-source-t.c
> +#endif
Done.

2017-06-14 12:18 UTC, odiszapc commented
@indutny @refack I'm done. The last question is how does `repo@^1.0.0` semantics work? How does gypkg decide which version to use?

2017-06-14 12:40 UTC, refack commented
> @indutny @refack I'm done. The last question is how does git://repo@^1.0.0 semantics work? How does gypkg decide which version to use?

Like @indutny said it uses `semver` version range rules (Code: https://github.com/gypkg/gypkg/blob/master/lib/gypkg/server.js#L494, Ref: https://docs.npmjs.com/getting-started/semantic-versioning), that is `^x.y.z` mean any `semver-minor` equal or greater, and `~x.y.z` is any `semver-patch` equal or greater...

(I think you commented you did see tags, mini-test does have tags, GitHub just isn't intuitive in showing them)
![image](https://user-images.githubusercontent.com/96947/27132463-ffe234aa-50dc-11e7-8e08-31d8710c503a.png)

2017-06-14 18:17 UTC, indutny commented
Landed in b3ae076, thank you!

2017-06-14 18:17 UTC, closed without merging